# Gitのエイリアス
alias a='git a'
alias gitadd='git a'
alias s='git s'
alias ss='git s'
alias b='git b'
alias c='git c'
alias d='git d'
alias l='git l'
alias lo='git lo'
alias show='git show'
alias sh='git show'
alias wip='git w'
# glsとかは brew install coreutils
alias ll='gls -alivF --color=auto --group-directories-first'
alias cp='cp -aiv'
alias mv='mv -iv'
alias rm='grm -Iv'
