include:
  - '**/*.rb'
exclude:
  - '**/spec/**/*'
  - '**/vendor/**/*'
  - '**/.bundle/**/*'
  - '**/node_modules/**/*'
  - '**/log/**/*'
  - '**/tmp/**/*'
require: []
domains: []
# reporters:
#   - rubocop
#   - require_not_found
require_paths: []
max_files: 1000
