alias b='git b'
alias c='git c'
alias d='git d'
alias g='git'
alias gits='git s'
alias l='git l'
alias lo='git lo'
alias s='git s'
alias show='git show'
alias wip='git w'

# glsとかは brew install coreutils
alias ll='gls -alivF --color=auto --group-directories-first'
alias cp='cp -aiv'
alias mv='mv -iv'
alias rm='grm -Iv'
