require:
  - rubocop-performance
  # - rubocop-rspec
  # - rubocop-rails

AllCops:
  # チェック対象外
  Exclude:
    - "**/vendor/**/*"
    - "**/.bundle/**/*"
    - "**/node_modules/**/*"
    - "**/bin/**/*"
    - "**/log/**/*"
    - "**/tmp/**/*"

# 人生でクォートを直している時間は一体どれだけになるのか
Style/StringLiterals:
  EnforcedStyle: double_quotes

# コメントは日本語で書いてもよい
Style/AsciiComments:
  Enabled: false

# [String, String, String]は%w表記でなくてもよい
Style/WordArray:
  Enabled: false

# [Symbol, Symbol, Symbol]は%i表記でなくてもよい
Style/SymbolArray:
  Enabled: false

# 空メソッドは1行で記述しなくてもよい
Style/EmptyMethod:
  Enabled: false

# Hashのリテラル後のカンマを許す（複数行時）
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Arrayのリテラル後のカンマを許す（複数行時）
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# 一行の長さチェック
Metrics/LineLength:
  Max: 80 # => デフォルト値:80
  Exclude:
    - "**/db/migrate/*" # => チェック対象外

# class, module前にて説明を明記
Style/Documentation:
  Exclude:
    - "**/db/migrate/*" # => チェック対象外

# クラスは小さく心がける
Metrics/ClassLength:
  Exclude:
    - "**/db/migrate/*" # => チェック対象外

# モジュールは小さく心がける
Metrics/ModuleLength:
  Exclude:
    - "**/db/migrate/*" # => チェック対象外

# メソッドは小さく心がける
Metrics/MethodLength:
  Exclude:
    - "**/db/migrate/*" # => チェック対象外

# メソッドはシンプルに心がける
Metrics/AbcSize:
  Exclude:
    - "**/db/migrate/*" # => チェック対象外
