# Gitのエイリアス
alias a='git add .'
alias s='git s'
alias b='git b'
alias c='git c'
alias d='git d'
alias l='git l'
alias lo='git lo'
alias ss='git show'
alias show='git show'
alias reset='reset'
alias rebase='rebase'
alias cp='cp'
alias commit='commit'
alias comit='commit'
alias commmit='commit'

# glsとかは brew install coreutils
alias ll='gls -lv --all --inode --classify --color=auto --group-directories-first --time-style=long-iso'
alias cp='cp -aiv'
alias mv='mv -iv'
alias rm='grm -Iv'
